### ISSUE TITLE
$upload_path and external links

### ISSUE THREAD

**Issue by premax** [lazymofo/datagrid#17]
There is a tiny issue with this declaration and its explanation in line 71 of lazy_mofo.php library:
`public $upload_path = 'uploads';            // required when using --image or --document input types

The thing is that this variable is used not only in input types, but in output too.
For example:
 
```
   function html_document_output($file_name){
        // purpose: if exists, display document link
        // returns: html

        if(mb_strlen($file_name) > 0)
            $html = "<a href='$this->upload_path/$file_name' target='_blank'>" . $this->clean_out($file_name, $this->grid_ellipse_at) . "</a>";

        return $html;

    }

```

Now let’s assume that I need to setup an external link on my grid.

It is currently impossible to setup external link, because all the links will look like http://myLazyMofosite/upload/http://external.site.com (in default setup) 
or http://myLazyMofosite/http://external.site.com if we clear $upload_path variable.

Do not know if this is intended behavior, but for my purposes I have to modify the function:

```
    function html_document_output($file_name){

        // purpose: if exists, display document link
        // returns: html

        if(mb_strlen($file_name) > 0)
            $html = "<a href='$file_name' target='_blank'>" . $this->clean_out($file_name, $this->grid_ellipse_at) . "</a>";

        return $html;

    }

```
Now my external links are made up correctly.

**Comment by lazymofo** [comment]
In the design I assumed the documents would be in the same place as the
uploads. I'd like to keep this for backward compatibility.

Moving forward, I suggest you create a custom output control if you need to
link to a unique path, or extend and overide the method.
http://lazymofo.wdschools.com/#defining_custom_input_and_output_controls

Thanks,
Ian

**Comment by premax** [comment]
Well I'd at least modify function html_document_output(), it currently returns undefined string in some cases what generates lot of stuff in error log.

Currently there is:
```
    function html_document_output($file_name){

        // purpose: if exists, display document link
        // returns: html

        if(mb_strlen($file_name) > 0)
            $html = "<a href='$file_name' target='_blank'>" . $this->clean_out($file_name, $this->grid_ellipse_at) . "</a>";

        return $html;
```
    }

I suggest replacing the code with following snipet to avoid returning undefined $html variable:

```
    function html_document_output($file_name){

        // purpose: if exists, display document link
        // returns: html

        if(mb_strlen($file_name) > 0)
{
            $html = "<a href='$file_name' target='_blank'>" . $this->clean_out($file_name, $this->grid_ellipse_at) . "</a>";
           return $html;
}
else
 return false;
}
```

**Comment by lazymofo** [comment]
Doh! I missed that. Fixed now.
Thanks again!
