### ISSUE TITLE
special chars in query string - preg_match_all with PREG_OFFSET_CAPTURE and UTF-8

### ISSUE THREAD

**Issue by raffaelj** [lazymofo/datagrid#18]
If I use any special characters like German Umlauts (äöü) in a sql query I get an error because lazy_mofo removes `order by` in the wrong place. It took me a while to find the issue. `PREG_OFFSET_CAPTURE` doesn't care about special chars.

My temporary workaround:

I added a new function `mb_preg_match_all` to lm (copy-paste from [here](http://de2.php.net/manual/en/function.preg-match-all.php#71572)) and changed `preg_match_all` on lines 844 and 1690 to `$this->mb_preg_match_all`.

Before I forget about it - thanks for this great piece of code. I try to write a small application with it and your datagrid saved me a lot of time.

**Comment by lazymofo** [comment]
Thanks for submitting this issue. I'm on holiday right now, but I'll look
at this when I return.

**Comment by lazymofo** [comment]
raffaelj,Can you send me a copy of a query that would cause a problem?I
can't replicate the issue. preg_match_all seems to yeild the same results
regardless of what characters I use.Here's a script you can use to test the
output differences between preg_match_all and mb_preg_match_all:
https://pastebin.com/q9PpzdbL-Ian

**Comment by raffaelj** [comment]
I didn't have much time the last days and your pastebin said "Page Removed". But here is a testcase on my localhost:

```php
// lm settings, pdo connection, html template...

$lm->table = 'Buchhaltung';
$lm->identity_name = 'ID';

// working query [1] with correct filtered output
$lm->grid_sql = "select * from  Buchhaltung where Zusatztext like '%sphäre%'"; 

// not working query [2]
// $lm->grid_sql = "select * from  Buchhaltung where Zusatztext like '%sphäre%' order by ID";

echo '<pre><code>';
print_r($lm->grid_sql);
echo '</pre></code>';

$lm->run();
```

output of [2]:
```
select * from  Buchhaltung where Zusatztext like '%sphäre%' order by ID

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'o limit 0' at line 1
sql: select * from Buchhaltung where Zusatztext like '%sphäre%' o limit 0
arr_sql_param: Array
(
)

Sent From: get_columns

Notice: Undefined variable: columns in E:\github\buchhaltung\buchhaltung\tests\lazy_mofo.php on line 1702
```

The problem:
```
// it should cut the whole "order by"
// because of wrong byte counting the "o" of "order by" destroys the query
sql: select * from Buchhaltung where Zusatztext like '%sphäre%' o limit 0
```

**Comment by lazymofo** [comment]
Thanks for your help!! I was able to reproduce the issue and I implemented
the suggested fix.

**Comment by raffaelj** [comment]
Thanks for the mention in the changelog. It was a pleasure to help you and I'm a bit proud of contributing my first bugfix ever after using so much open source software in the last years :)

I tested the new version and it works. Let's close this issue.
