### ISSUE TITLE
text input for paging in giant datasets at the bottom of page doesn't work

### ISSUE THREAD

**Issue by raffaelj** [lazymofo/datagrid#21]
While translating your code I recognized the text input fields for paging in giant datasets and tested it. The one on the top of the page is working correct. If I try to enter a page number in the form at the bottom and press the go button it picks the value from the text input field at the top of the page.

**Comment by lazymofo** [comment]
Ah ha! Another bug... I'll look at that issue soon. Thanks!

**Comment by raffaelj** [comment]
Sorry for finding bugs ;-) and thanks for the [fix][1]. I tested it with your demo file and my already existing giant test database. Clicking on both buttons works now. Pressing <kbd>Enter</kbd> triggers the update button. But this is a behavior I can live with.

[1]: https://github.com/lazymofo/datagrid/commit/c392c0c6167241b254221fd0d3b7937689e1e06d#diff-e7b0c8fb1b7ffd082adc08718aa8b9cd
