### ISSUE TITLE
Adding/Editing Error: Checkboxes are returned unchecked if error occurs in another field

### ISSUE THREAD

**Issue by jmh-code-php** [lazymofo/datagrid#22]
I have two form input checkbox controls defined as:

$lm->form_input_control['event_sd_dance_program'] = "select 'Student Level-MS', 'Student Level-Mainstream' union select 'MS', 'Mainstream' union select 'PL', 'Plus' union select 'A1', 'Advanced 1' union select 'A2', 'Advanced 2' union 
     select 'C1', 'Challenge 1' union select 'C2', 'Challenge 2' union select 'C3', 'Challenge 3' union select 'C4', 'Challenge 4' union select 'C5', 'Challenge 5' union select 'RD', 'Rounds'; --checkbox"; 

$lm->form_input_control['event_rd_dance_program'] = "select 'I', 'Phase 1' union select 'II', 'Phase 2' union select 'III', 'Phase 3' union select 'IV', 'Phase 4' union 
     select 'V', 'Phase 5' union select 'VI', 'Phase 6'; --checkbox"; 

If I raise an error with any on_insert_validate field in either an Add form or an Edit form, such as:

$lm->on_insert_validate['event_date'] = array('/.+/', 'Missing Event Date', 'Required Field'); 

then the any selected checkboxes are cleared (returned unchecked).   

Am I missing something or is this a bug?

**Comment by raffaelj** [comment]
Hello,

It looks like a bug. I did a bit testing and I got:

`Notice: Array to string conversion in ********\datagrid\lazy_mofo.php on line 1371`

I [forked](https://github.com/raffaelj/datagrid) and [fixed](https://github.com/raffaelj/datagrid/commit/52a9716d5e57d954ce50a112c4c33a23779cd397) it. Would you test it with my modification, please? If it works well I'll make a pull request.

**Comment by lazymofo** [comment]
Raffael,

I wonder when this bug was introduced. I'm sure this worked at some point.
Oh well..
It's fixed now. I implemented a fix similar to yours.

Thanks,
Ian

**Comment by raffaelj** [comment]
Ah - after hitting the commit button I thought about implode but didn't want to change it again...

I didn't recognize it before and I never tried checkboxes.

Fun fact: The bug exists since [your initial commit](https://github.com/lazymofo/datagrid/commit/e8f33649c44dd43de88f9ee19b02fbeb65877f69#diff-e7b0c8fb1b7ffd082adc08718aa8b9cdR1325).

**Comment by jmh-code-php** [comment]
Thank you for the update and quick turnaround, Raffael.   The checkboxes behave properly now after another field does no pass validation.  You can close this issue.
