### ISSUE TITLE
Full File Path is Not Returned with --document Feature in Add or Update Grids 

### ISSUE THREAD

**Issue by jmh-code-php** [lazymofo/datagrid#23]
I defined a field using a '--document' type and only the filename is returned.  In order to upload the file to a MySQL blob type field (during on_insert or on_update user function), I need the entire file path and file name from the client PC but the file path is not returned.   

BTW, have you ever considered adding the ability to upload a file to a SQL blob field?  This would not necessitate my having to define a function to do this in an on_insert or on_update user function.  Just a thought.

**Comment by lazymofo** [comment]
I'll consider adding a blob type that adds the file to the database. In
general it's seen as a bad practice to add files into a database, but I can
understand cases where small binaries would be okay.

As far as the entire client file path is concerned, it's not available due
to browser security.
https://stackoverflow.com/questions/14915470/how-to-get-client-side-path-of-the-uploded-file

**Comment by jmh-code-php** [comment]
Thank you for the response, Ian.   You can close this issue.
