### ISSUE TITLE
Formatting Fields 

### ISSUE THREAD

**Issue by jmh-code-php** [lazymofo/datagrid#26]
Is there any way to format a field that is being displayed?  For example, I would like to change the output text to a different text size and bold the font.

**Comment by lazymofo** [comment]
CSS should take care of your needs.

If the field is on the form, editing 1 record, then use the class name of
the input.
View the html source, or use Chrome inspector to see the class names.

If the text is on the grid, where all the records are displayed at once,
you can target the column with css nth-child.

If you really need conditional formatting there is also custom input output
controls.
https://rawgit.com/lazymofo/datagrid/master/index.html#defining_custom_input_and_output_controls
