### ISSUE TITLE
Issue with search.

### ISSUE THREAD

**Issue by ArisTeo13** [lazymofo/datagrid#27]
Hi, I'm just new here and I like your work, Lazymofo really makes things easy in CRUD.
I have been exploring 'uri path' and its working perfectly in adding & updating data but I noticed in searching it seems to fail. 

**Here's what I did:**
// uri path
$lm->uri_path = "admin.php?tab=2"; 

**When I update data, the url is working properly:**
localhost/administrator/admin.php?tab=2&action=edit&id=1829&

**But when I do a search, tab=2 is gone.**
localhost/administrator/admin.php?_search=cruz&action=search

I wonder if I'm doing things right. Hope you can help me with this. Thank you.

**Comment by lazymofo** [comment]
I may be wrong, but I don't think I intended the uri_path parameter to
contain parameters.

Try this instead:

$lm->querystring = 'tab';

This will tell the class to carry around that parameter when posting,
searching, etc.
