### ISSUE TITLE
Upload images turns up black

### ISSUE THREAD

**Issue by H-d-t** [lazymofo/datagrid#31]
Hi, I'm finding your datagrid very useful. Got few tiny problems, main one is that uploaded images works but sometimes they end up as black images. Both the thumbnail and the main images, both just a black image. It doesnt happen for all images, but it happens on mobile and pc for me. 

fyi, these are the parameter values I'm using for the upload:

	$lm->image_quality=100;
	$lm->upload_allow_list ='.jpg .jpeg .png';	
	$lm->upload_width = 300;
	$lm->upload_height = 300;
    $lm->upload_crop=true;

sometimes the image also gets flipped 90% degrees to the left.

**Comment by H-d-t** [comment]
i've been doing some digging myself, I've added this line because it seems at time the jpeg does not get recognized as a valid jpeg file. in those cases we have to:

$image= imagecreatefromstring(file_get_contents($file_name));

i dont know if that's the correct fix, but it seems to work at the mooment.

**Comment by lazymofo** [comment]
I can't replicate this issue yet. I'll see what I can figure out. 
I suspect there's something wrong with your GD install. What version of gd is installed? phpinfo() will tell you. I should add a check in the script for GD.

You may also want to check to see if the image is getting uploaded. 
Set the $lm->form_input_control['field_name'] = '--document'. This will just upload the image without crop/resize. Make sure it's getting uploaded. 

I think it will be one of these 2 issues.
