### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by fredtempez** [lazymofo/datagrid#32]
Hi,

I have a mistake charging translation file i18n  :

In the connect file on root folder : 
`$lm_data = new lazy_mofo ($dbh, 'fr-fr');`

I have to change line 188 to make it run :
`if(!file_exists("vendor/datagrid/i18n/{$i18n}.php"))`

Otherwise, there is an error "file not found".

Did I miss something ?

**Comment by lazymofo** [comment]
This is a bug, I've just been testing with a different paths where it worked. I'll fix this soon. 
Thank you for submitting the issue!   

On a side note I accidentally deleted the demo.php file. It's restored now.

**Comment by lazymofo** [comment]
Update released. This issue should be fixed now.
