### ISSUE TITLE
Second collum to wide (Table Doesent fit in Container)

### ISSUE THREAD

**Issue by SchnitzelPommes** [lazymofo/datagrid#33]

**Comment by lazymofo** [comment]
It looks like you figured out the issue.

The best thing to do in this case is define the fields visible on the
opening grid view and limit the columns to just 5 or less.

See demo.php for how $lm->grid_sql defines the SQL statement used on the
grid.

Note, the last column in your statement must be the identifier/id field.

**Comment by SchnitzelPommes** [comment]
Is there any way to make the grid vertical scrollable ?

**Comment by lazymofo** [comment]
Sorry, I don't know what you mean? Doesn't your browser automatically add
vertical scroll bars? Maybe you can post an example of what you are looking
for.
