### ISSUE TITLE
$uri_path property for search function

### ISSUE THREAD

**Issue by drstakz** [lazymofo/datagrid#34]
Hi, 
I using experimental $uri_path property =) and looks nice when I using include pages for functions add, edit, delete.. But when I want to use function search so I lost my variables from URI. 

What I see, uri_path is also use for search button, but when is used variables are lost. 
Some ideas?

Thanks
Z

**Comment by lazymofo** [comment]
Hello Z,

The only time I've needed $uri_path was with WordPress plugin trickery.

I think you want to use query_string_list instead. It's a comma delimited
list of variables to carry around.

So if you add this line of code the page will carry around variables it
receives on the query string.

// carry around data in foo and bar
$lm->query_string_list = 'foo,bar';

// now a url like when the page loads, foo and bar will be carried from
screen to screen.
mypage.php?foo=1&bar=2

The names must not conflict with the form variables though.

-Ian

**Comment by drstakz** [comment]
Hello, correct. Query_string_list is a way. When I found uri_path so I overlooked this option.

Thanks!
Z.
