### ISSUE TITLE
action field name saves with 'update'

### ISSUE THREAD

**Issue by kazmotron** [lazymofo/datagrid#36]
not a big deal but ...

if a table contains a varchar field named field 'action' lazy-mofo will write the word "update" when you save

**Comment by lazymofo** [comment]
I should have used _action for the input instead. Most of the names used by the library are prefixed with a _ to prevent these kinds of issues. I would fix this now, but I don't want to break backward compatibility. 

I should add a check to halt the library if a reserved name is used and mention this in the docs. 

Thanks for the feedback!
