### ISSUE TITLE
Not Responsive! 

### ISSUE THREAD

**Issue by githubsrinath** [lazymofo/datagrid#4]
Dear Developer,

I have used and recommended most of my friends to use LazyMofo for simple CRUD applications.

One small issue which always bother me is ,  the screens are not responsive!  Its very difficult to view in Small hand held devices.  I wish it had some sort of Bootstrap integration to it.  

Is there any plans?  

Many thanks.
Srinath Rao

**Comment by lazymofo** [comment]
Thanks for your input. Maybe I'll make a Bootstrap fork soon. I get a fair
number of requests for Bootstrap compatibility.
