### ISSUE TITLE
Dependency for --select 

### ISSUE THREAD

**Issue by githubsrinath** [lazymofo/datagrid#40]
Hi , 

I have car make and model two different List fields.
Make is selected from the query from the table using "--select "

But for the model, I need to provide dynamic make which is just selected from the previous field, cause it needs to show only the model belong the car make.

How this can be achieved in Lazy mofo. 

In simple How to pass previous field value to select statement for --select?

Thanks very much.

**Comment by lazymofo** [comment]
Hello Srinath, 

The data grid does not have this feature, but it's not too hard to add in with some jQuery. Attached is a demo. 

[ajax_select.zip](https://github.com/lazymofo/datagrid/files/2697362/ajax_select.zip)

-Ian
