### ISSUE TITLE
Redirection to specific div in webpage

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#41]
Dear iansoko

I wanted to ask regarding redirecting after a grid is updated or a new record is added/edited etc.

Since i load my LMDatagrid in a specific div of my page without reloading the page, (using js and ajax), i want the edit forms or the updated grid to appear in the original div that the LMdatagrid was loaded.

I noticed that you do have a feature "$redirect_using_js" but i cannot find an example of its use in your documentation.

Can you direct me somewhere ?

**Comment by lazymofo** [comment]
By default, LM will redirect with server-side header(). In some cases this
causes a problem, and a plain old javascript client-size
<script>window.location.href='blah';</script> is needed.

Either way, LM Datagrid is not meant to be used with ajax. Not to say it
won't work, but you'll have to have some ninja level javascript skills to
make it work ajax style.

If you're just loading an edit/form view and want to post via ajax, that's
not too hard.
If you're loading the opening grid view, then you have lots of work to do,
altering behavior for edit, delete, search, pagination.

A good alternative would be an iframe. An iframe will look like a popup
ajax modal, but code wise, it will work without any hacks. I think you
should explore iframe in this case.

Good luck!

**Comment by tplevrak** [comment]
Thank you for your answer.

I am still very new to web design so i will definitely take a look to iframes, (a new word for me today).

My experience is mostly in MsAccess and VBA where i make some database applications.

In MsAccess datagrids are ready by default with all the functionality and none of the scripting. You just place a visual element, and everything is integrated in one solution. It is very handy but on the downside your hands are tied up and you cannot do anything more than is provided. Plus it only works on Windows.

That is the reason i am exploring web application. Ultimately i would like to have such a functionality with php/apache/mysql, so i am trying to see how can i get to something similar.

Best Regards.
