### ISSUE TITLE
New localization file for Greek Language el-gr.php

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#42]
Dear iansoko

I created a localization file for the Greek language, el-gr.php, (tested it and seem to work ok), for the i18n folder and i do not know how to send it to you.

I am not an experienced github user  so i am not sure if i should try something through the github repository or just email it to you.

**Comment by lazymofo** [comment]
Excellent! Thanks for the translation!
Just email it over. I'll try to address your other question later tonight.

-Ian
iansoko@gmail.com

**Comment by tplevrak** [comment]
Ok, i have already emailed the file to you.

If i missed something, please let me know to fix it.

Best Regards

**Comment by tplevrak** [comment]
Thank you very much iansoko !
