### ISSUE TITLE
Image upload_path possible issue

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#43]
Hi !
I have been trying to use the image type in a form, so that the user can upload an image to the record.

Although i have set up the upload_path variable to my relative image path, i keep getting the error that the path either does not exist or it is not writable.

*"Error: Error: Unable to move uploaded file. Make sure path: /tf_images/tf_contact_images exists and is writeable. Try chmod 0755 (or 0777 is you must) on the destination path.*

*Sent From: get_upload()"*

Of course the path exists and it is writable.

I tried to use a full path and, although it shouldn't have, it worked. 
The images were uploaded and the thumbnails were created at the right places.
But then the images could not be displayed as the path is obviously wrong, since a relative path is required.

After i changed the path back to the relative form, the images were displayed correctly.

They were also displayed correctly using the relative path and writing the name of the image file directly to the database.

So i think there maybe is an issue here with the form of the path while uploading and displaying an image.

Or hopefully i am missing something ?

Best Regards

**Comment by lazymofo** [comment]
Hi Plevrakis,

It's hard for me to debug your issue. Upload is working for me.
This library is meant to use relative paths, so please stick to relative.

check upload filesize phpinfo()
check upload_tmp_dir in phpinfo()
echo sys_get_temp_dir();

try adding this code in upload_file(), right before the
move_uploaded_file() call.

if(!file_exists($tmp_name)){
    $notice .= "Error: expected temporary file $tmp_name does not exists.
Make sure " . sys_get_temp_dir() . " exists and is writable. PHP settings
could be preventing uploads.\n";
    return;
}

Hope this helps!
-Ian

**Comment by tplevrak** [comment]
Dear Ian,

Thank you very much for your immediate response.

Unfortunately i could not make it work with relative paths.

I inserted your code to the point you suggested but no Errors poped up, so i guess $tmp_name has a value.

Of course i understand that you cannot debug my issue since there are too many things you do not know about my setup. (plus, it my job to do that :-) )

Trying to think of a possible reason for the issue i thought that it could be maybe because i

- using a developer pc and not a proper server
- use a symbolic link in /var/www/html,
- because i use php 7.2 (although i did not have any issue until now)
- i totally am unaware of some settings of php
- maybe because i load the datagrid inside an iframe (as per your advice which, by the way, it works perfectly regarding navigation)

For now i made it work with a workaround.

1. i supplied full path to $upload_path and $upload_thumb like this:
*str_replace($_SERVER['SCRIPT_NAME'],"",$_SERVER['SCRIPT_FILENAME']).'/tf_images/tf_contact_images';*

2. i declared two more variables in your class named
*$tf_upload_path='/tf_images/tf_contact_images';*
*$tf_upload_thumb='/tf_images/tf_contact_thumbs';*
and i initialized them with the relative paths

3. When i supply the full path, everything, (upload/resize/thumbnail/database), works ok except the appearance of the images in the grid, so instead of using $upload_path and $upload_thumb, i used $tf_upload_path $tf_upload_thumb in function html_image_input().

So now everything works as it should.

I realize that this is not a proper solution, but i am sure that i will stumble upon the same issue sometime in the future and maybe then i can debug it successfully and return and fix it properly.

I am still very new to php/mysql so i guess i have a lot more work to do (i am still trying to figure out how to use the datepicker)

So, thank you very much and when i have any new development i will let you know.

Thank you for your time.
Best Regards

**Comment by lazymofo** [comment]
Plevrakis,

Yes, it seems there are cases when 2 sets of paths are needed, one for
uploading, the other for linking/viewing. I'll look into this issue further.

Thanks,
Ian
