### ISSUE TITLE
how can make ajax 

### ISSUE THREAD

**Issue by flutterpro** [lazymofo/datagrid#44]
hey bro . 
how can make ajax the grid ? or make requests to modalbox ?

**Comment by flutterpro** [comment]
or multilpe image upload ?

**Comment by lazymofo** [comment]
There are no ajax features or modals, but I'm sure many things can be hacked together though.

Multi image upload is tricky and requires a lot of extra code. I can make a multi image demo if you like. It requires a custom input, and hooks in after_insert/update/delete_user_function.

**Comment by flutterpro** [comment]
thanks dude . so how can add html element before inputs on form ?
the problem is about add leaflet map before an element with javascript that have issue . i want add html from php.

**Comment by lazymofo** [comment]
use javascript or use a custom input
https://htmlpreview.github.io/?https://github.com/lazymofo/datagrid/blob/master/index.html#defining_custom_input_and_output_controls
