### ISSUE TITLE
full command in custom function

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#46]
Just curious, did this update break your code?

I feel like any fix results in a worse outcome.

 For a little background, this parameter is not used too often. It holds the control name, which used to look like this "--my_control". In the new version the string comes through as "my_control".

If I "fix" this depending on how the control is setup (old --prefixed, versus new array), then output will vary on setup, which I don't like.

I'd rather the output be consistent and possibly break a little backward compatibility in this case.

_Originally posted by @lazymofo in https://github.com/lazymofo/datagrid/issues/45#issuecomment-524134076_

**Comment by sarangtc** [comment]
> For a little background, this parameter is not used too often. It holds the control name, which used to look like this "--my_control". In the new version the string comes through as "my_control".

Before the new format of form/grid input/output controls,
the call format was:
$lm->form_input_control['weird_data'] = '--my_user_function';
which I used as
$lm->form_input_control['weird_data'] = 'select my customsql; mycustom string; --my_user_function';

the function format was:
function my_user_function($column_name, $value, $command, $called_from)
where
$column_name: field name
$value: field value  
**$command: full command** as defined in the arrays: form_input_control, grid_input_control, or grid_output_control
$called_from: which function called this user function; form, or grid

so 
when I called this $command variable in the custom function, I used to get
'select my customsql; mycustom string; --my_user_function'
returned to me (not just '--my_user_function')
which was a useful way of passing custom sql or parameters to the function, so one function fits all, like you do with select and selectmultiple

with the new format, command just returns the function name (i.e. type)!

is there a way to get the new format to pass the "full command"?

**Comment by lazymofo** [comment]
Sarangtc,

Thanks for being persistent. I see there's more of a loss of data than I
thought before. Give me a little time and I should be able to fix this.

Thanks!!!
-Ian

**Comment by sarangtc** [comment]
looking at the class
I think the previously suggested change (changing $type to $control in the call_user_func) is how people expect it to act in the **new** format. I may be wrong though.

for **backward compatibility** I think some if/case statement may need to be added in the "modernize_control" function or where it is called at the start of the run function
(but as you mentioned, "I'd rather the output be consistent and possibly break a little backward compatibility in this case." I, personally, am ok with changing my existing functions to match the new format as long as I get the entire string/array. But that said, with everyone in mind, backward compatibility is always good)

**Comment by lazymofo** [comment]
This update is completed.

version 2019-09-25
------------------
  Altered $command in custom input controls. Better backward compatibility
relating to 2019-01-10 update. Thanks sarangtc
  Added ability to define absolute upload and thumb paths. Requested by
someone a long time ago.

**Comment by sarangtc** [comment]
great.
Backward compatibility is 100% ok.

But, for the NEW format, if I have understood properly, the **new** documentation for custom function says:
> // $command: **array** defined in the control; rarely needed

but at the moment the updated code does not return **the array**, but only returns **a string** (the string declared in the 'type' key of the array).
so, if I am not mistaken, I think that the default line that reads:
> $legacy_control = $type;

should be "$legacy_control = $control;"
in both the "get_input_control" and "get_output_control" functions in order to return the [full] array

**Comment by lazymofo** [comment]
One week later.... Sorry I'm so slow!

I've adjusted the code to what you're saying. I agree with your plan.
Thanks for the guidance!

**Comment by sarangtc** [comment]
Great.
Now, with this new format allows for the creation of a lot of generic functions with user options.
I have many I would like to share.
some similar to the JQuery UI Datepicker in the help documentation but for select2 and fastselect
with some nice options,
I am also in the process of making some functions for an ajax datagrid
....

I would like you to look at them first. see what you think. May be have a separate include for such jquery/javascript functions, or extended class, or in main class.

How can I send them to you?
