### ISSUE TITLE
public suite of custom functions

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#47]
The new format of functions allows for the creation of a lot of generic functions with customizable user options.

I have some I would like to share, some similar to the JQuery UI Datepicker in the help documentation but for select2 and fastselect with some nice options like ordering, onclick/onload .... (created to improve the performance issue that some browsers have when loading multiple dropdowns with many options)

I am also in the process of making some functions that would turn lm into an ajax datagrid, possibly with some sort of concurrent multiuser support ....

It may be nice to have a place for such functions to be shared.
Possibly a separate include for such jquery/javascript functions, or perhaps an extended class,
or these could be added to the main class if felt useful for all.

I would like you to look at them first. see what you think.
How can I send them to you?

**Comment by lazymofo** [comment]
hey sarangtc,

I'm not really interested in adding features at this point. The library has
evolved a lot. I feel like less is more at this point. Send what you like
and I'll take a look.

I would consider adding more demos though.

Thanks!
-Ian

**Comment by sarangtc** [comment]
post them here?

**Comment by lazymofo** [comment]
Whatever you prefer. You can email me directly if that's easier.

**Comment by RenZ0** [comment]
Hi sarangtc, I am very interested in your changes, as I also play with lm in this way :)
You may want to fork and push your changes on github ?
Or you would prefer to send by email ?

**Comment by sarangtc** [comment]
> Hi sarangtc, I am very interested in your changes, as I also play with lm in this way :)
> You may want to fork and push your changes on github ?
> Or you would prefer to send by email ?

Still have a couple of bugs I have to fix. it's taking me a while with though. There are a couple of bug fixes that I need raise tickets for too.

**Comment by KirSergeev** [comment]
I don't' want to start new issue - just want to say thank you  lazymofo for this php class.  
Thank you very much.
