### ISSUE TITLE
Current date / time auto population and csv import

### ISSUE THREAD

**Issue by lorol** [lazymofo/datagrid#49]
Hi, first, thank you for the great and clean code!
More as an example request, could you please recommend what is the best way to populate now() value in date datetime types as a default or so?
Also for testing (again as sample, not the class), it may be valuable to be able to re import the CSV file back to database,
Any advice will be appreciated.

**Comment by lazymofo** [comment]
Funny, I don't have a good built-in way to populate a date with now(). I'll
think about how this can be done for a future version.

I'd recommend altering your database to populate the dates for you.
You might want to set form_input_control['field_name'] =
"readonly_datetime" in this case.
https://stackoverflow.com/questions/5818423/set-now-as-default-value-for-datetime-datatype/5818452

If you want to do in within this library the only good way I can recommend
is

$lm->after_insert_user_function = 'set_create_date';
$lm->after_update_user_function = 'set_create_date';
...
function set_create_date($market_id = 0){

    // noticed an issue here, after_update_user_function does not pass id
like insert version does
    // this may be changed soon if i can make the fix backward compatible,
regardless this sample will work
    if($market_id == 0)
        $market_id = $_POST['market_id'];

    global $lm;
    $sql = "update market set create_date = now() where market_id =
:market_id";
    $sql_param = array(':market_id' => $market_id);
    $lm->query($sql, $sql_param);

}



here's a full demo
https://pastebin.com/k182hjTZ

**Comment by lorol** [comment]
Thank you for the time spent!
After reviewing what I actually need ... :) I believe the auto-population of date / datetime "by default" is better to be done at client side (say by JS means) instead of server-side or database engine means.
In any case, timezones and localization etc. are nightmare.  

I also played with datepicker suggestion, works well - but needs to be localized - there are many i18 samples. Also I tried this standalone datetime JS pure picker:  https://github.com/owenmead/Pikaday.git  

It works as well ... still some string formatting issues to resolve.

**Comment by lazymofo** [comment]
Not related to the library, but on the subject of timezones, you probably
already use this strategy...
I just keep the database and server UTC +00:00. Users have specific their
timezone.
Then for any user output run the datetime thru convert_tz().

**Comment by lorol** [comment]
I believe you can close the issue case.
The part of importing from CSV is unrelated to the datagrid and I found some examples.
Regards
