### ISSUE TITLE
PHP Notice error

### ISSUE THREAD

**Issue by mbunyan** [lazymofo/datagrid#5]
Undefined variable: port in lazy_mofo.php on line 2263
Undefined variable: context in lazy_mofo.php on line 555
Undefined index: HTTPS in lazy_mofo.php on line 2256
Undefined variable: port in lazy_mofo.php on line 2263

these do nto appear to be affecting functionality, just annoying.
I can remove the errors by declaring variable with empty or null values, but having difficulty working out what may fail by doing so.

Mike B

**Comment by lazymofo** [comment]
Pesky notices! I'll fix or silence those items shortly.
Thanks for posting.
-i
