### ISSUE TITLE
 Implementing cascading dropdowns

### ISSUE THREAD

**Issue by cadencetech** [lazymofo/datagrid#50]
Is there a way to make cascading drop downs in the edit panel?  For example, Country, State(within Country), City (within State)

**Comment by lazymofo** [comment]
Hello,

There's no built-in way to update select dropdown dynamically.
You just have to be skilled in javascript to make it happen. Here's simple
demo attached if you'd like to expand upon this.
[ajax_select.zip](https://github.com/lazymofo/datagrid/files/3816041/ajax_select.zip)
-Ian

**Comment by cadencetech** [comment]
Ian,

Thank you!!!  Works perfectly!
