### ISSUE TITLE
Blank multiselect2 works with grid but not with form

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#53]
First of all, this is not an issue with the native html MULTISELECT that is default in lazymofo.
If I use a custom function that calls select2 (js) I have some issues with blank fields as follows:
if there is NO DATA in the field when a form/grid is loaded, and the field is left blank - there is no issue.
If there IS DATA in the field when a form/grid is loaded if I then blank the field I get the following:
no data for that field is passed in the post data, not even a fieldname = [""], which causes the following:
if I am on a FORM, the lack of post data causes the field not to be updated and so the form is repopulated with success but the field has the data it had prior to clearing.
If I ma on a GRID, the field updates perfectly with the data being cleared (even though there is no post data for that field-id combination)

I couldn't get my head around how this is done in the sql_update_grid function so that I could suggest an update accordingly for the sql_update function.

Can you help?

**Comment by lazymofo** [comment]
Select2 is just a javascript addon that changes a select or selectmultiple
into a new UI, there's nothing that needs to be added regarding LM
Datagrid. I've tested select2 on the form and grid. It seems to work fine.

Just add some java script telling the library where to apply select2.
Example:
<script>
    $(document).ready(function() {
        $('select.lm_market_name').select2();
    });
</script>

**Comment by sarangtc** [comment]
select2 **does** work in both, that is not the issue.
BUT there seems to be a slight error.

After further testing, I realised that it is not an issue with just select2 but any multiselect that was previously 1 or more values and needs to be cleared by unselecting the selected values.

to reproduce the issue:
STEP 1:
in the input controls, define a multiselect field in both form and grid:
e.g.
$lm->form_input_control['Authors'] = array('type'=> 'selectmultiple', 'sql' => 'select Author_ID, Author from Author_Master order by Author;');
$lm->grid_input_control['Authors'] = array('type'=> 'selectmultiple', 'sql' => 'select Author_ID, Author from Author_Master order by Author;');

STEP 2 (OPTIONAL): 
add the following javascript to the end of the file after the php closes:
<script>
    $(document).ready(function() {
        $('select.lm_Authors').select2();
    });
</script>


STEP 3:
open grid/form and select multiple values (1 or more) from the options for any record
and save (you should see the records selected after the update)

STEP 4:
open the record in the **edit form** and ctrl+unselect the values that were previously selected
then save
you will **still see** the values selected

if step 4 is done in **grid** view, the values clear successfully.


After further testing:
For grid view both a) unselecting selected values and b) selecting blank option can be used to clear mutliselect
BUT The only way of clearing the multiselect in the form view is by selecting the blank option at the top (this is not available in select2) i.e. (a) is not an option so select2 then fails here

What is in the sql_update_grid  function that isn't in the sql_update function which helps the sql_update_grid function successfully update in both scenarios?

**Comment by lazymofo** [comment]
Thanks!
 I'll see if I can reproduce this issue. I'll probably take a look at it
tomorrow or over the weekend.

**Comment by lazymofo** [comment]
This should be fixed now in the latest update.
Funny that I never noticed the behavior of blank selectmultiple not posting
data before.
Thanks for reporting the issue!

**Comment by sarangtc** [comment]
All verified and working as expected. Thanks.
Thanks for listening.
