### ISSUE TITLE
group_concat limit override option suggestion

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#54]
sometimes **large** group_concats (useful for getting subquery data into a cell) fail due to mysql limits. This can be overridden, but would be nice to have an option in the class.

Just like you have
`public $charset_mysql = 'utf8mb4'; `

and then in the query function, you have:
```
        if(!$this->set_names){
            $sth = $this->dbh->prepare("set names $this->charset_mysql");
            $sth->execute();
            $this->set_names = true;
        }
```

You COULD also add a similar parameter:
`public $group_concat_max_len = '1000000';`
or 
`public $group_concat_max_len = ''; // leave blank for default, or 1000000 for large group_concats`

and add this to the query function
```
        if(!$this->set_group_concat_max_len && !empty($this->group_concat_max_len)){
            $sth = $this->dbh->prepare("SET @@group_concat_max_len = $this->group_concat_max_len");
            $sth->execute();
            $this->set_group_concat_max_len = true;
        }
```

**Comment by lazymofo** [comment]
sarangtc,

*i'll look at all these issues you posting soon. *
*thanks! they all seem like valid issues i should address.*

*thanks,*
*ian *

**Comment by lazymofo** [comment]
I feel it's more straightforward to just write:

$lm->query("SET @@group_concat_max_len = 9999");

compared to:

$lm->group_concat_max_len = 9999;

I'm going to skip this feature for now.

**Comment by sarangtc** [comment]
understood
