### ISSUE TITLE
compulsory order by

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#56]
I think it should be mentioned in the documentation somewhere that if order by is used within any internal select or group_concat in the grid query, then lazymofo detects that as the last 'order by' and breaks the query, so need to compulsorily add an order by to the entire query, at least something like `order by 1`

**Comment by lazymofo** [comment]
I mentioned this issue in the demo.php code and the documentation.
I hope this is sufficient.
Thanks!!
