### ISSUE TITLE
Master Detail

### ISSUE THREAD

**Issue by axelmoe** [lazymofo/datagrid#57]
At first many thank for this fantastic class.
My question:
Is there a way to create Master/Detail forms?
e.g. an invoice has a invoice header and n invoice lines

KR
Axel

**Comment by lazymofo** [comment]
Sorry, there are no features to display child/detail data. You'll have to
just manually display the data at the bottom of a form.

maybe something like this at the bottom of the script:

$market_id = intval(@$_GET['market_id']);
$details = "";
if($market_id > 0){

    $sql = "select * from other_table where market_id = :market_id";
    $sql_param = array(":market_id" => $market_id);
    $result = $lm->query($sql, $sql_param);
    echo "<pre>" . $lm->clean_out(print_r($details, true)) . "</pre>";
}

**Comment by sarangtc** [comment]
I come across this need often 
and what I do is have a view/edit details button in one column which opens a popup div with another lazy_mofo page for the invoice_lines table in an iframe.

I also have a group_concat in the main page that previews the lines.

**Comment by lazymofo** [comment]
Cool. Sounds like you found a solution!

**Comment by sarangtc** [comment]
if you are happy with the solution please close this issue

**Comment by axelmoe** [comment]
nice solution
