### ISSUE TITLE
Can i ignore a text input field on record save/new ?

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#58]
Hallo Ian.

I have a question about how i can achieve a certain functionality i want.

The sort version of my question is this:

Can i have an input field, which does not belong to the lm source table, in a lm grid that will not be included in the sql when the changes are saved ?

Now i know that is not very explanatory so here goes the long version of my question :

Basic Example:

I have a main table 

"contacts_table"

This table has an id field and a contact name field e.g. 

"contacts_table.contact_id"
"contacts_table.contact_name"

I also have a table with tasks

"tasks_table"

that table has a contact_id field so that a task can be assigned to a contact, and of course a task field.

"tasks_table.task_id"
"tasks_table.task_name"
"tasks_table.contact_id"

I produce a view with the two tables linked on the common contact_id field and the new tasks view looks like

"tasks_view.task_id"
"tasks_view.task_name"
"tasks_view.contact_id"
"contacts_table.contact_name"

Now, because the user must be able to change the contact assigned to the task, i have setup a lm datagrid with all the fields of the "tasks_view".
The source table, (for updates/deletes etc.) of the lm is of course the "tasks_table".

The "contact_id" field is a text input field, but naturally the user is not supposed to know the contact id.
So, the "contact_name" field is a text input field with jquery ui autocomplete, so that the user can change the contact easily by autocompleting the contact name.
As soon as the contact name is changed, the contact_id field is also updated with the new contact id with the use of javascript.

All the above is happening on the grid, not on the form.

My problem is that if i try to save the change, it returns an error because, obviously, the "contact_name" field does not belong to the "tasks_table".

Is there a way that i can save the change but not include the contact_name field in the sql ?

I tried the exclude_field method but the results are the same.

Thanks in advance.

**Comment by lazymofo** [comment]
If I understand correctly, this would be easy to do on the form side, using
after_insert_user_function
after_update_user_function, but you want to add related field from the
grid.

I would suggest the following:
1. add additional "temporary" fields to the contact table; like
contacts_table.temp_task_name
2. using after_update_grid_user_function, move the temp_task_name into the
task table.

$lm->after_update_grid_user_function = 'after_update_grid_user_function';

function after_update_grid_user_function(){

    global $lm;

    $sql = "insert into tasks(contact_id, task_name) select contact_id,
temp_task_name from contacts_table where temp_task_name is not null";
    $lm->query($sql);

    $sql = "update contacts_table set temp_task_name = null";
    $lm->query($sql);
}

**Comment by tplevrak** [comment]
Thank you very much for the answer and the time spent on it.

Actually i am already using "dummy fields" as a workaround, and i do not use a function. 

The lm just saves the value in the dummy field along with the useful values and i just let the dummy field be, i am  just not using any of it's data.

Plus this works as expected  with the grid.

I was just hoping for a more clean solution so that i will not have to use fields as "dummies".
(if someone is to study the db in the future, is going to be really confused), 
(that person would probably be me of course).

Like the "exclude_fields" method, but actually excluding the field from the sql  action writing the data to the source table.

Anyway, thanks again for your time and also thank you for the awesome lm php grid !!!
