### ISSUE TITLE
Pagination ?

### ISSUE THREAD

**Issue by DiGi36** [lazymofo/datagrid#59]
I played around with and forked this project. **Has anyone tried to add pagination to the project?** When I connected my data ( ~2000 records) , it just scrolled forever.

**Comment by lazymofo** [comment]
Yes, there is already pagination. It should be on by default.
Here's a live demo if you'd like to see.
http://lmdatagrid.hopto.org/

I'm not sure what kind of bug you might be experiencing. Let me know if you
find anything.

**Comment by DiGi36** [comment]
I got it to work but how do you adjust it? Each page contains 200 records. Is there a way to make each page like 25 ?

**Comment by lazymofo** [comment]
There are a lot of properties you can set for settings. Check the code.
$lm->grid_limit = 25; // 25 records a page
