### ISSUE TITLE
Checkbox behaviour unusual

### ISSUE THREAD

**Issue by mbunyan** [lazymofo/datagrid#6]
The demo shows column 'is_active' as tinyint(1) with default NULL. I would have expected to see '0', zero.
The update or add work by applying NULL.
I would like to ensure '0' is recorded, have you a tip here please.
If the column tinyint(1) requires not null, it will not update or add new, because the script tries to apply null for '0', even if a default value '0' is provided in the db table config.

Mike B

**Comment by lazymofo** [comment]
Your request is logical, but I was just trying to be consistent; blank text, dates, numbers all are saved as null. 

I'll try to add a feature where you can define the casting based on column name.
In the meantime you can try some ugly hacks:

```
// form updates and inserts, cast is_active
$_POST['is_active'] = intval(@$_POST['is_active']);


// grid updates, cast is_active checkbox 
foreach($_POST as $key => $val){

    if(!strstr($key, '-checkbox-'))
        continue;

    $column_name = str_replace('-checkbox', '', $key);
    $_POST[$column_name] = intval(@$_POST[$column_name]);
}    
```

thanks for the input!
-i

**Comment by lazymofo** [comment]
I fixed the notices and added the feature to define casting based on column
names. See http://lazymofo.wdschools.com/#cast_user_function
