### ISSUE TITLE
Any option to make text clickable?

### ISSUE THREAD

**Issue by premax** [lazymofo/datagrid#60]
I need to refer from one mofo grid to another. I know that I can show full url and make it clickable, but this does not look nice. Is there any option to make a text clickable?
i.e. <a href="https://very-long-url.com/details.php?id=666">details</a>
(`<a href="https://very-long-url.com/details.php?id=666">details</a>)`

**Comment by lazymofo** [comment]
Of course anything can be added in javascript, but maybe you're looking for
something like this:

$lm->grid_output_control['weird_data'] = array("type" =>
"my_user_function"); // grid view - outputting one row

$lm->form_intput_control['weird_data'] = array("type" =>
"my_user_function"); // form - editing one record

function my_user_function($column_name, $value, $command, $called_from){

    // $column_name: field name
    // $value: field value
    // $command: array defined in the control, or string with legacy
syntax; rarely needed
    // $called_from: orgin of call; 'form', or 'grid'; rarely needed

    $value = intval($value);
    return "<a href='next_page.php?id=$value'>Next Page</a>";

}

// on a side note you might find the $lm->query_string_list property of
interest. You can carry variables on child pages in the query string to
help return to the parent.

**Comment by premax** [comment]
Thank you!  Your solutions works.

It looks that grid_output_function has changed in the last years, previously I have used it with double dashes - error messages are still there and there are misleading, ie. 

> "Output command or user function not found: --document. Be sure to prefix control type with 2 dashes --"

But now I had to remove the dashes:

```
//      $lm->grid_output_control = array('Link' => '--document');
      $lm->grid_output_control['Link'] = array('type' => 'document');
      $lm->grid_output_control['ISBN'] = array('type' => 'my_link');

```

But, nevertheless, is there any option to pass two arguments (values from two different fields, i.e. "id" and "value") to the function?

Now I can only have:   `"<a href='next_page.php?id=$value'>Next Page</a>"`;
But I'd like to have:  `"<a href='next_page.php?id=$id'>$Value</a>"`;

?

**Comment by lazymofo** [comment]
It's a hack, but you can do the following:

// if your db supports it, json_array would be better than a random
delimiter
select concat_ws('|', col1, col2) as ISBN from tablename...

$lm->grid_output_control['ISBN'] = array('type' => 'my_link'); // new style
syntax
$lm->grid_output_control['ISBN'] = '--my_link'; // old style syntax still
works

function my_user_function($column_name, $value, $command, $called_from){

    global $lm;
    list($col1, $col2) = explode('|', $value);
    $col1 = $lm->clean_out($col1);
    $col2 = $lm->clean_out($col2);
    return "<a href='next_page.php?id=$col1'>$col2</a>";

}

**Comment by premax** [comment]
> json_array

JSON_ARRAY and json_decode work perfectly, thank you

**Comment by premax** [comment]
> > json_array
> 
> JSON_ARRAY and json_decode work perfectly, thank you

The hack is good but it brakes CSV export (JSON array is exported and does not look good). 

Quick & dirty fix in export function, when json array is found, only the last value of array is exported to CSV (i.e. link description, not link URL)

```
        // loop thru data
        foreach($result as $row){

            $column_index = 0;
            foreach($columns as $val)
                if(is_array($a=json_decode($row[$val])))
                    echo $this->export_escape(end($a), $column_index++);
                else
                    echo $this->export_escape($row[$val], $column_index++);

            echo "\n";

```

**Comment by lazymofo** [comment]
You can specify alternate sql for the export.

if(@$_GET['_export'] == 1)
    $lm->grid_sql = "...";

**Comment by Juulsfar** [comment]
I made 2 functions in lazy_mofo.php (at the end),

Place this in your file.
$lm->grid_output_control['menu'] = array("type" => "my_href_new",  "export_ska.php?int_id="); 

int_id wil be the record number
Your field (in my case 'menu')  becomes a hyperlink.


[function.txt](https://github.com/lazymofo/datagrid/files/8612039/function.txt)
