### ISSUE TITLE
url / url_new support

### ISSUE THREAD

**Issue by saf001** [lazymofo/datagrid#61]
New to lazymofo and pretty rusty with my PHP. I added this:

        elseif($type == 'url')
            return "<a href='$value'>$value</a>";   
        elseif($type == 'url_new')
            return "<a href='$value' target='_blank'>$value</a>";           

to _get_output_control_ so that I could embed http links into the grid, from the db table.

It be a nice, generic, addition for others.

**Comment by lazymofo** [comment]
Thanks, I'm still considering this change.

If it's gets implemented the control name will be 'url_blank'.

**Comment by saf001** [comment]
Agree, url_blank makes more sense :-)
thanks

**Comment by premax** [comment]
It would be useful to add an option to declare link description different from URL.  
Similar issue: #60
