### ISSUE TITLE
Column size

### ISSUE THREAD

**Issue by paulderidder** [lazymofo/datagrid#62]
How can I set column sizes? The second cokumn in the grid is always too wide, even withvl dates or integers

**Comment by lazymofo** [comment]
css example

.lm_grid tr td:nth-child(2) { max-width: 100px; }

**Comment by juhacz** [comment]
Remove last line from style.css file.
#lm table.lm_grid tr td:nth-child(2) { min-width: 300px; }

**Comment by lazymofo** [comment]
thanks!! I don't know what that was doing in the default css. removed
