### ISSUE TITLE
postgres version proposal

### ISSUE THREAD

**Issue by mrlinux666** [lazymofo/datagrid#66]
i believe that a version to postgresql that already done, can be useful to add to the project, it is possible to share the postgresql version to you? thank u 
[lazy_mofo.txt](https://github.com/lazymofo/datagrid/files/4810150/lazy_mofo.txt)

just replace .txt to php

**Comment by lazymofo** [comment]
I consider this project to be in maintenance mode. I'm not really
interested in new features, just stability.
I'll check this out though, maybe you should add a repo and maintain it. I
can link to your project.
Thanks!

**Comment by RenZ0** [comment]
> i believe that a version to postgresql that already done, can be useful to add to the project, it is possible to share the postgresql version to you? thank u

Hello, nice idea as PDO helps in this way. Maybe you could provide a patch ? it will be easier to apply on any version.
I copied your file into git to see the diff but many end of lines have changed ; so output is not clean.
Please help us to see the real changes needed for the trick !

**Comment by mrlinux666** [comment]
Basically, you need to change the query to PostgreSQL standard, because they use MySQL Standard.

**Comment by lazymofo** [comment]
This project is in maintenance mode, no new features, just bug fixes. Sorry, no Postgres support.
