### ISSUE TITLE
Ampliamento

### ISSUE THREAD

**Issue by sroselli** [lazymofo/datagrid#68]
Hello Thank you very much for your contribution, I started studying it for a few days and it is really well done, congratulations. 

But I needed some help .... I would like to add on each line of the grid, next to the delete and modify keys, a grid key that would open a new datagrid that points to a new table. And also if instead of having the words **[modify]** and **[delete]** it was possible to insert keys in **graphic form**. 

I would be really grateful to you for this new contribution.

**Comment by lazymofo** [comment]
You can alter the links with these properties:

$lm->grid_edit_link   = "
<a
href='other_grid.php?action=edit&amp;[identity_name]=[identity_id]&amp;[qs]'><img
src='other_grid.png'></a>
<a
href='[script_name]action=edit&amp;[identity_name]=[identity_id]&amp;[qs]'><img
src='edit.png'></a>
";

$lm->grid_delete_link = "
<a href='#' onclick='return _delete(\"[identity_id]\");'><img
src='delete.png'></a>
";

By the way, there's an Italian translation available if needed.

$lm = new lazy_mofo($dbh, 'it-it');

**Comment by sroselli** [comment]
Hello and thank you for your suggestion, I applied the changes but maybe I didn't explain myself well, for this I apologize and I repeat my question: Once you click on the link (icon) you need to open a new grid that filters the results of a second table correlated and indexed with key to the source grid so that it can perform identical operations on the second table (modifications, deletions and insertions). Also for the purpose I have to use two different lazy_mofo (one for each grid I manage)? ... in practice it does not have to access the insertion but the visualization (grid), from where then to insert, modify and delete as in your project

**Comment by sroselli** [comment]
...in pratica non deve accedere con insert ma in visualizzazione griglia, da dove poi eseguire inserimento, modifica e cancellazione come appunto la griglia di partenza
