### ISSUE TITLE
Avoid NOTICE errors

### ISSUE THREAD

**Issue by SharmPRO** [lazymofo/datagrid#69]
First of all, thanks for you excellent work.

It would be possible to 'polish' the library to avoid all those 'NOTICE' errors?
... (isset($_REQUEST['action']) ? @$_REQUEST['action'] : '') ...
Thanks

NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1592 - Undefined index: action
 lazy_mofo->run, lazy_mofo->get_action
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:867 - Undefined index: _posted lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:868 - Undefined index: _search
lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:869 - Undefined index: _pagination_off lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:870 - Undefined index: _order_by
lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:871 - Undefined index: _desc
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:872 - Undefined index: _offset
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:873 - Undefined index: _export
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1905 - Undefined index: _order_by
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->delete_js, lazy_mofo->get_qs
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1905 - Undefined index: _desc
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->delete_js, lazy_mofo->get_qs
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1905 - Undefined index: _offset
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->delete_js, lazy_mofo->get_qs
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1905 - Undefined index: _search
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->delete_js, lazy_mofo->get_qs
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1905 - Undefined index: _pagination_off
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->delete_js, lazy_mofo->get_qs
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:883 - Undefined index: _success
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:996 - Undefined index: team
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:996 - Undefined index: default
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1041 - Undefined index: id
 lazy_mofo->index, lazy_mofo->grid
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1612 - Undefined index: sql
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1613 - Undefined index: sql_param
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1637 - Undefined index: default-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1639 - Undefined index: default-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1644 - Undefined index: default-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1649 - Undefined index: default-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1637 - Undefined index: active-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1639 - Undefined index: active-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1644 - Undefined index: active-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1649 - Undefined index: active-3
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1637 - Undefined index: default-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1639 - Undefined index: default-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1644 - Undefined index: default-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1649 - Undefined index: default-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1637 - Undefined index: active-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1639 - Undefined index: active-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1644 - Undefined index: active-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control
NOTICE: wp-content/plugins/spro_online_registration/includes/datagrid/lazy_mofo.php:1649 - Undefined index: active-444
 lazy_mofo->index, lazy_mofo->grid, lazy_mofo->get_input_control

**Comment by lazymofo** [comment]
Thanks, I'll look into fixing these notices soon.
In the meantime consider adding code to temporarily disable the notices.

error_reporting(E_ALL & ~E_NOTICE);

**Comment by SharmPRO** [comment]
thanks

**Comment by lazymofo** [comment]
Hello,

I cannot replicate these notices and your notices don't correspond to code
in the current version.
What version are you using? This issue may have already be resolved in the
current version.

-Ian
