### ISSUE TITLE
Input using selectmultiple not with dropdown but search and suggestions

### ISSUE THREAD

**Issue by grows888** [lazymofo/datagrid#7]
Dear developer,
Is it possible to make the input using selectmultiple by search and showing suggestion instead of dropdown?

**Comment by lazymofo** [comment]
I'm not clear on what you're asking but I'll take a guess. It sounds like
you're asking for functionality in something like select2.
https://select2.github.io/examples.html

LM data grid does have a selectmultiple\* input control, so and you can add
on the select2 javascript to get the fancy interface.

Just be aware that the LM datagrid just stores the selectmultiple
selections as a delimited list. If you want the data saved in a normalized
manner you'll have to handle it manually with something like this:

```
$lm->after_insert_user_function = 'sync_selections';
$lm->after_update_user_function = 'sync_selections';
$lm->after_delete_user_function = 'sync_selections';


function sync_selections($market_id = 0){

    // untested sample code

    global $lm;

    // get identity - insert will pass in the id
    if($market_id == 0)
        $market_id = round($_POST['market_id']);

    // delete old selections
    $sql = 'delete from market_country where market_id = :id';
    echo $sql;
    $lm->query($sql, array(':id' => $id));

    // get data
    $arr = $_POST['country_id'];
    if(!is_array($arr))
        $arr = array();

    // insert selections
    foreach($arr as $key => $val){
        $sql = 'insert into from market_country(market_id, country_id)
values (:market_id, :country_id)';
        $lm->query($sql, array(':market_id' => $market_id, ':country_id' =>
$country_id));
    }

}
```
