### ISSUE TITLE
Custom Values for CheckBox Input Control

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#73]
Dear Ian,

I would like to ask you if there is a way that i can define the checkbox input control values to some custom ones that i need.

I saw that when the checkbox control is checked, the value saved in the database is 1 and when it is not checked the value is Null.

I need to store values Yes for checked and No for unchecked.

I also went to the documentation but the only extra info is the

_checkbox | input checkboxes. values are stored in a delimited list. sql is optional. sql_param is optional._

so i tried to use the SQL but although it works, it also shows multiple checkboxes which does not look as  i want it to.

Thank you in advance

Best Regards and always thank you for your amazing work.

**Comment by lazymofo** [comment]
Hello Plevrakis,

You could do one of the following work-arounds.

1. Add a user defined function to fix the data

$lm->after_update_user_function = 'cast_zero';
$lm->after_insert_user_function = 'cast_zero';

function cast_zero($id = 0){

    global $lm;

    if($id == 0)
        $id = $_POST['id'];

    $sql_param = array(':id' => $id);
    $sql = "update table set field = coalesce(field, 0) where id = :id";
    $lm->query($sql, $sql_param);

}



2. Add javascript to capture the submit event, check all unchecked
checkboxes on .lm_form, change value value to 0.

$('.lm_form form').on('submit', function(){
    $('input[type=checkbox]:not(:checked)').val('0').prop('checked', true);
});

**Comment by tplevrak** [comment]
Dear Ian,

Thank you once again for your prompt response.

I checked out your solutions but i concluded that it is simpler for me to just change my values to 1/null from Yes/No.

Best Regards
