### ISSUE TITLE
PHP Error: Class 'lazy_mofo' not found in C:\xampp\htdocs\...

### ISSUE THREAD

**Issue by anpcc** [lazymofo/datagrid#74]
Hello, 
I premise that I am new with PHP and fresh from subscribing to github. I installed XAMPP portable with PHP ver. 7.3.7 for Windows 64 bit, with which I have already started a portal in which I wanted to insert your Lazy_Mofo DataGrid, but at the line of `include('lazy_mofo. php');` I first get the output on screen of the code of your Class lazy_mofo.php and then the PHP error: "`( ! ) Fatal error: Uncaught Error: Class 'lazy_mofo' not found in C:\xampp\htdocs\test\demo1.php on line 41`" due to the line:
`$lm = new lazy_mofo($dbh, 'it-it');` or `$lm = new lazy_mofo($dbh, 'en-us');` or `$lm = new lazy_mofo($dbh);`  .
    Otherwise, using `require_once __DIR__. "lazy_mofo.php";` (instead of include), I get the double error:
"`( ! ) Warning: require_once(C:\xampp\htdocs\testlazy_mofo.php): failed to open stream: No such file or directory in C:\xampp\htdocs\test\demo1.php on line 10`" and immediately after: 
"`( ! ) Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\testlazy_mofo.php' (include_path='\xampp\php\PEAR') in C:\xampp\htdocs\test\demo1.php on line 10`" (without output on screen the Class Code lazy_mofo.php). 
    Can you tell me where I'm wrong?   Thanks a lot
Andrea

**Comment by Psychi1** [comment]
Hi, 

are you sure with you include statement. I guess there is an additional space after the period. Your `include('lazy_mofo. php');` should be `include('lazy_mofo.php');`

Bye Uwe

**Comment by lazymofo** [comment]
I'm not seeing this issue in the source example:
https://github.com/lazymofo/datagrid/blob/81485c5cac789daf507f9bedbd08e49643f61b93/demo.php#L40

**Comment by Psychi1** [comment]
Hi,

in @anpcc code (as written in the issue) is an space in the include statement. Not in the source sample. 

Bye
