### ISSUE TITLE
mysql 8.0 capitalization of column_name and column_default in information_schema

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#76]
with mysql 8.0 
the query
`select column_name, column_default from information_schema.columns where column_default != 'NULL' and column_default is not null and table_name = :table and table_schema = database()` 
returns a result set with 2 columns with capitalized names  'COLUMN_NAME' and 'COLUMN_DEFAULT'
(mysql 5.7 used to return 'column_name' and 'column_default')

so now, **if we have error reporting on**, we get this error:

Warning: Undefined array key "column_name" in lazy_mofo.php on line 1816

Warning: Undefined array key "column_name" in lazy_mofo.php on line 1817

Warning: Undefined array key "column_default" in lazy_mofo.php on line 1817

so to solve for mysql 8 need to change lines 1816 and 1817 (in version 2021-06-03) to:
`
                if(!array_key_exists($row['COLUMN_NAME'], $this->form_default_value))
                    $this->form_default_value[$row['COLUMN_NAME']] = trim($row['COLUMN_DEFAULT'], "'"); 
`

**but to make it backward compatible:**
could **change query in line 1810 instead** to:
`
select column_name as column_name, column_default as column_default  from information_schema.columns where column_default != 'NULL' and column_default is not null and table_name = :table and table_schema = database()
`

**Comment by lazymofo** [comment]
hi sarangtc,

thanks for posting this. I'll look into this issue soon.

-ian

**Comment by sarangtc** [comment]
another backward compatible workaround is to use the array_change_key_case function
i.e. between line 1812 and 1813 add:
`array_change_key_case($result);`

**Comment by lazymofo** [comment]
Sorry, I'm not clear on why we need lowercase on the results of this query.
The default and column name properly match the expected result.

drop table test;
create table test (id int, Str varchar(10) default 'Foo');
select column_name, column_default from information_schema.columns where
column_default != 'NULL' and column_default is not null and table_name =
'test' and table_schema = database();

+-------------+----------------+
| column_name | column_default |
+-------------+----------------+
| Str         | 'Foo'          |
+-------------+----------------+

**Comment by sarangtc** [comment]
Is this result from mysql  Ver 8.0.25 ?
this is what I get
`
+--------------------+-------------------+
| COLUMN_NAME        | COLUMN_DEFAULT    |
+--------------------+-------------------+
| parent_category_id | 0                 |
| active             | 2                 |
| last_updated_by    | 0                 |
| last_updated_date  | CURRENT_TIMESTAMP |
+--------------------+-------------------+

`

**Comment by lazymofo** [comment]
My bad. I'll test with MySQL 8. I was using MariaDB.

**Comment by lazymofo** [comment]
this should be fixed now. thanks again for submitting the issue.

-ian
