### ISSUE TITLE
limit 0 error

### ISSUE THREAD

**Issue by softhdcomp** [lazymofo/datagrid#77]
When I try to "edit" or "add" record i get an "... sql limit 0 error" and i guess $columns variable are corupt and error are in line 758 and 1757. Some years ago i use lazy mofo well (and i thanks for that). I come back to lazy mofo because is small and 1 file. Please help me to understand whats wrong. Display grid works ok.

**Comment by lazymofo** [comment]
Hello,

Sorry, I can't determine a potential issue from your description.
If you can provide your code and a "show create table [tablename]" of your
database I can look into the issue.

Thanks,
Ian
***@***.***

**Comment by softhdcomp** [comment]
Thanks for your prompt reply. I used a minimal grid show sample. I atached now some picture.
![add_error](https://user-images.githubusercontent.com/86819411/124342601-ab152380-dbcd-11eb-9f14-0d51eb2ed55b.jpg)
![edit_error](https://user-images.githubusercontent.com/86819411/124342603-ac465080-dbcd-11eb-826a-cbd48dbd95d5.jpg)
![php_file](https://user-images.githubusercontent.com/86819411/124342604-acdee700-dbcd-11eb-8f63-c6ab1a2582fd.jpg)
![table_structure](https://user-images.githubusercontent.com/86819411/124342605-acdee700-dbcd-11eb-89fd-77f49d30e44e.jpg)
![working_grid_show](https://user-images.githubusercontent.com/86819411/124342606-ad777d80-dbcd-11eb-8dd4-5795c3454ba3.jpg)

**Comment by softhdcomp** [comment]
Another informatian that can help to identify the problem is that de lazy_mofo.php from 16-10-2017 work perfect. The files from 26-07-2020 and newer fails in the same manier like in the picture.

**Comment by g05357005** [comment]
Found same problem on php 7.3

when $lm->form_sql is not set , 
$lm->get_columns('forms') will display such error.



solution: don't use simple mode :)

**Comment by lazymofo** [comment]
Thanks, I'll look into this issue tonight.

**Comment by lazymofo** [comment]
thanks again for submitting this issue! pretty embarrassing. ugh.
it should be fixed now :)

-ian

**Comment by softhdcomp** [comment]
Thanks !! Work ok. Thanks again !! Lazy Mofo is like an old good friend. Small, quick, easy to use. Same tool from big company are big, complicate to use and for sure not cheap.
