### ISSUE TITLE
Error Message when click Edit , Delete 

### ISSUE THREAD

**Issue by seaboat69** [lazymofo/datagrid#78]
Hi All , I am a newbie PHP - I using a Lazymofo /datagrid  - I need a help . Thank for every help .

My problem is : 

When click Delete in Grid ==> Error: missing identity_value Sent From: delete()
When click Edit in Grid ==> Missing identity_id. If using a custom form_sql statement be sure to include the identity.

My data is : 

Database Test
Table dmkh 
colum :
ma_kh varchar(18),  Primary key
ten_kh varchar (96),
ma_so_thue varchar(32),
dia_chi varchar(120),
tk varchar(16),
e_mail varchar(48) ,
doi_tac varchar(48) ,
tk_nh varchar(32)

**Comment by lazymofo** [comment]
Tables must have an id field.

In MySQL:
*alter table dmkh add id int not null auto_increment primary key first;*

Then inside the php:
*$lm->identity_name = 'id';*

If you're using a custom grid_sql statement the last column needs to be the
id

// optional
$lm->grid_sql =
"
select
ma_kh,
ten_kh,
ma_so_thue,
dia_chi,
tk,
e_mail,
doi_tac,
tk_nh,
*id*
from dmkh
";

**Comment by seaboat69** [comment]
Thank for your help - I follow your advice and i have fix error .
