### ISSUE TITLE
Display enum as select on edit form

### ISSUE THREAD

**Issue by fluxxus** [lazymofo/datagrid#79]
Hi, designer here who barely knows PHP needs a lil help.

I have two quick questions:

1. In my db I have an enum field `enum('processing', 'completed')`, with a default value of processing.
I have a hard time displaying it as a select or radio on the edit form. 

2. If i use auto-generated id which is also a primary key as my `$lm->identity_name` my pagination is not displayed using select element, but rather just a text input.

But if I try with a different table that doesn't have auto-generated id as primary key, but some other field, pagination is fine and paginating the data with native select element. 
I have attached an image that shows pagination without select element.

![Screenshot 2021-09-15 at 00 58 02](https://user-images.githubusercontent.com/3802291/133344986-9c26a7ed-0e05-4647-b3b9-cd8e4b7a7122.png)

**Comment by lazymofo** [comment]
1. Here's how you would define the input control:

// make a sql statement that will return 2 options; processing and completed
// this is populate the options in the dropdown select

$lm->form_input_control["field_name"] = array("type" => "select", "sql" =>
"select 'processing' as val, 'processing' as opt union select 'completed'
as val,  'completed' as opt");


2. If there are over 100,000 records the pagination control is switched
from using a dropdown select to the text entry in your screenshot.

**Comment by fluxxus** [comment]
Thanks for the quick response. All good now, thanks once again!
