### ISSUE TITLE
duplicate record feature request

### ISSUE THREAD

**Issue by freezah** [lazymofo/datagrid#80]
Would like to kindly request a feature enhancement to the datagrid by adding 'duplicate' button next to 'edit' and 'delete', allowing user to duplicate specific record and instantly edititing it before saving as new record.

**Comment by lazymofo** [comment]
This is a good idea. I'll consider adding this feature.
In the meantime here's a little hack you can use to get similar
functionality.

// append a copy button next to delete
// place this code after $lm->identity_name has been defined
$lm->form_delete_button = $lm->form_delete_button . "<input type='submit'
value='Copy' class='lm_button'
onclick='document.forms[0].{$lm->identity_name}.value=0;
document.forms[0].action.value=\"edit\"; return true;'>";

**Comment by sarangtc** [comment]
Nice.
I think the suggestion was intended for the grid view though.

**Comment by lazymofo** [comment]
I'm probably not going to implement further features. I consider the project in maintenance mode. 

Here's an ugly hack to achieve the desired functionality:  

```
// append an additional link next to delete, similar html to the edit link but with an additional 'sub_action' param
$lm->grid_delete_link = $lm->grid_delete_link . "<a href='[script_name]action=edit&amp;sub_action=copy&amp;[identity_name]=[identity_id]&amp;[qs]'>[copy]</a>";


<script>
// when sub_action=edit is sent, post data over to the add form
window.addEventListener('load', (event) => {
    var params = new URLSearchParams(window.location.search);

    if(params.get('sub_action') == 'copy'){
        document.forms[0].market_id.value = 0;  // change me to match your identity name
        document.forms[0].action.value = 'edit';
        document.forms[0].submit();
    }
    
});
</script>

```
