### ISSUE TITLE
custom update sql

### ISSUE THREAD

**Issue by jmbanda** [lazymofo/datagrid#81]
Greetings! Great contribution! I am wondering if there is a nicer way to pass a custom update SQL query other than hacking it directly in the main sql_update function. 

Thanks in advance!

**Comment by lazymofo** [comment]
If you need to run additional SQL you can place it in an event hook:

https://htmlpreview.github.io/?https://github.com/lazymofo/datagrid/blob/master/index.html#on_insert_update_delete_events

https://htmlpreview.github.io/?https://github.com/lazymofo/datagrid/blob/master/index.html#on_insert_update_delete_events

on_insert_user_function
on_update_user_function
on_delete_user_function
on_update_grid_user_function

after_insert_user_function
after_update_user_function
after_delete_user_function
after_update_grid_user_function
