### ISSUE TITLE
Usage with PHP 8.1

### ISSUE THREAD

**Issue by fluxxus** [lazymofo/datagrid#82]
I am getting lots of errors/warnings when using with PHP version 8.1. It seems that passing null to non-nullable parameters of built-in functions is not acceptable anymore. 

Just a few examples:
`Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in...`
`Deprecated: mb_detect_encoding(): Passing null to parameter #1 ($string) of type string is deprecated in...`
`Deprecated: mb_convert_encoding(): Passing null to parameter #1 ($string) of type array|string is deprecated in...`

Is there an easy fix for these or? Thx

**Comment by lazymofo** [comment]
Hi!

Thanks for pointing this out! Newer versions of php are becoming
more strict on their input.
I'll install php 8 and see if I can address these warnings.
For the time being you can disable deprecations messages if desired.

-Ian

**Comment by fluxxus** [comment]
Ok, thanks for the tip! I am quite a noob when it comes to PHP, but your library is a life saver for me :)

**Comment by lazymofo** [comment]
I believe all these warnings have been fixed for php 8.1 compatibility. Let
me know if you see any others.

Thanks!
-Ian
