### ISSUE TITLE
Add BOM - Byte Order Mark to export (for windows/excel utf8 compatibility)

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#83]
I would like to suggest adding the BOM to the start of the export to provide compatibility for windows/excel so utf8 data shows properly.
e,g, to show "પ્રમુખ" instead of "àªªà«àª°àª®à«àª–".

for this, all you have to do is add:
`echo chr(0xEF).chr(0xBB).chr(0xBF);`

to the export function after the 4 header lines.

if you think that this is not applicable to all users, you could have a true false BOM option like the other export options (filename, delimiter etc.)

**Comment by lazymofo** [comment]
sorry for the slow reply. I'm looking into this issue. thanks!

**Comment by sarangtc** [comment]
OK. that's fine. Here is a link for more information if necessary.
https://www.w3.org/International/questions/qa-byte-order-mark

**Comment by sarangtc** [comment]
Is there anything I can help with? 
As mentioned before, the solution is simple:
all you have to do is add:
```echo chr(0xEF).chr(0xBB).chr(0xBF);``` to the export function, after the 4 ```header``` lines.
I have tried and tested this.

the decision that you have to make is whether to implement this fix permanently, optionally or not at all.

the main line of concern in the link provided before (https://www.w3.org/International/questions/qa-byte-order-mark) is:
The UTF-8 BOM offers reliable encoding detection, since it is extremely short and stable, works in XML and HTML, and works whether your page is read over the network or not (unlike HTTP declarations).

**Comment by lazymofo** [comment]
I've added the bom.
I don't fully understand the topic, but I'll trust your findings and add it
here to help Excel.
Thanks again for the help!
