### ISSUE TITLE
Question about Javascript execution from lazymofo

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#84]
Dear Ian,
I hope that you are and doing ok.

I wanted to ask you about javascript execution from within the lazymofo datagrid.

More specifically, i have a table with invoices and i want to be able to print each invoice from the grid.

I have made a column, not in the database but with a function as you have instructed me in one of my previous questions to you. 

The column includes either a button that executes a JS function onclik, or a link that has the JS function in the href attribute.

`<button onclick="javascript:tf_invoice_print($value, 'pdf');">🖨</button>
<a href="javascript:tf_invoice_print($value, 'pdf');" target=\"_blank\">🖨</a>`

Both ways do not work, the JS does not run.

Maybe there is a safety feature that prevents JS from running ?
It is something else ?

Thank you in advance

Best Regards

**Comment by lazymofo** [comment]
>>Maybe there is a safety feature that prevents JS from running ?

I can't think of anything that would prevent your javascript. View the
source to make sure your output is as expected, also,
use your web browser's inspector (control+shift+i) to look for errors in
the console.

by the way, this code is invalid:
<a href="javascript:tf_invoice_print($value, 'pdf');" target=\"_blank\">🖨
</a>

you probably want something like this:
<a href="#" onclick="tf_invoice_print($value, 'pdf'); return false;"
target=\"_blank\">🖨</a>

good luck!

**Comment by tplevrak** [comment]
Dear Ian,

Thank you once again for the prompt and accurate response.

Your code works. (Of course !)

The weird thing is that mine is not wrong too.
I saw this syntax on w3schools.com

If i use it with a built in function of JS e.g. alert(); it also works.

It does not work with my custom function though as it does not work with the use of the button tag.

Any way, the syntax that you suggested works ok with my custom function so all is good.

As you obviously noticed i am not experienced in JS so i stumble upon such issues.

Thank you very much, again.

Best Regards
