### ISSUE TITLE
How to make image manditory?

### ISSUE THREAD

**Issue by githubsrinath** [lazymofo/datagrid#86]
I would like to make image mandatory.

I tried both the option...

 $lm->form_input_control['pcir_image1'] = array('type' => 'image', 'optional' => false);

and 

 $lm->on_insert_validate['pcir_image1']   = array( 'regexp' => '/.+/', 'error_msg' => 'Atleast Image 1 must be uploaded', 'placeholder' => 'Image 1 is required', 'optional' => false);

but both didn't work.  

Please help me if i am missing something. 

thanks.

**Comment by xcuidi** [comment]
Intenta con esto:

		$lm->form_input_control['pcir_image1'] = '--image';
		$lm->on_insert_validate['pcir_image1'] = array('/.+/', 'Atleast Image 1 must be uploaded', 'Image 1 is required'); 
		$lm->on_update_validate=$lm->on_insert_validate;

**Comment by githubsrinath** [comment]
tried. but no luck! / intentó. pero sin suerte!

Now even if the image file is attached application, "At Least Image 1 must be uploaded"

**Comment by githubsrinath** [comment]
I have also tried validating with a user-defined function.  I noticed that _POST would not have the value of image data types. Hence we can not find out if the value is empty. 

Here is the tried code:

`function my_validate(){
            if(empty($_POST['pcir_image1']))
                return false; // fail
            else
                return true; // success
}
`
It always falls to an empty string; even the file is uploaded.

Is it supported in Lazy Mofo?   

Srinath Rao
www.evenforce.com

**Comment by xcuidi** [comment]
the "pcir_image1" field is string ? may be...

**Comment by githubsrinath** [comment]
Yes its  string
pcir_image1 | varchar(255)



<br class="Apple-interchange-newline">
</body>
</html>

**Comment by lazymofo** [comment]
The built-in validator doesn't work for file uploads.

Here's an example using demo.php where we add a custom validation function to check for an uploaded image.
We could have also added a similar function into a on_insert hook. 
```

// paste into demo.php, right after "copy validation rules". we want this validation only for inserting a record, not updates.

$lm->on_insert_validate['photo'] = array('regexp' => 'photo_required', 'error_msg' => 'JPG or PNG Upload Required', 'placeholder' => '', 'optional' => false);

function photo_required(){

    $input_name = 'photo';

    if(!isset($_FILES[$input_name]['size']))
        return false;

    $size = intval($_FILES[$input_name]['size']);
    $tmp_name    = $_FILES[$input_name]['tmp_name'];
    $file_name   = $_FILES[$input_name]['name'];

    if($size == 0 || strlen($file_name) == 0)
        return false;

    $ext = strtolower(substr($file_name, -4));
    if(!($ext == '.jpg' || $ext == '.png'))
        return false;

    return true;
        
}

```
