### ISSUE TITLE
[Feature request] Make the display length of columns configurable

### ISSUE THREAD

**Issue by ouryperd** [lazymofo/datagrid#88]
I have been through the source and CSS and can't find a value to tweak. My text is cut off at 33 chars.

![image](https://user-images.githubusercontent.com/29674819/199728221-71556d26-694e-4869-8dfe-9b6c58ae0296.png)

**Comment by lazymofo** [comment]
Plain old css can adjust column widths.

table.lm_grid tr td:nth-child(1) { width: 60%; }
table.lm_grid tr td:nth-child(2) { width: 40%; }

If you have grids on multiple pages you can wrap the grid in a div with a
page name specific class:

<div class='c_<?php echo substr(__FILE__, 0, -4);?>'>

then, in your css you can address the grid of a specific page like this:

div.c_demo table.lm_grid tr td:nth-child(1) { width: 60%; }

**Comment by ouryperd** [comment]
That worked for column width, but the text content is still truncated.

![image](https://user-images.githubusercontent.com/29674819/203796778-d712f5e2-173e-48d8-87a2-c7c3e98a028d.png)

**Comment by fluxxus** [comment]
@ouryperd I think this is what you want, just set overflow ellipsis to 0 -   `public $grid_ellipse_at = 0;`

**Comment by ouryperd** [comment]
@fluxxus ahh, what a champ. Thank you ! That is it.
