### ISSUE TITLE
Not really an Issue, more of a question

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#89]
Dear Ian,

I was wondering if there is a way when i am in the grid and add a new record, that i would entirely skip the form and return immediately to the grid and show the new record in the grid with the old ones.

Thank you in advance and have a happy holiday !!!

**Comment by xcuidi** [comment]
try whit this
    $lm->return_to_edit_after_insert = false;
    $lm->return_to_edit_after_update = false;

**Comment by tplevrak** [comment]
Thank you for the reply Ian.

But i have already tried this and it does not do what i would like.

In more detail, what i would like to do is this:

I have a grid in which all of the fields are editable.

So i do not want to use the form at all.

When i press the new record button, i want it to just refresh in grid with the new record added with default values and i will continue the record edit from the grid.

**Comment by lazymofo** [comment]
Hello,

The grid doesn't currently have this functionality, but I'm sure it could
be hacked in with some creative js.
If I get some time, I'll try to make you a little demo on how it could be
done.

-Ian

**Comment by tplevrak** [comment]
@xcuidi Sorry i thought your reply was Ian's and thank you for it.
I was in a hurry and did not notice that is was you.

@lazymofo 
Ian, thank you very much.

I know that you have lazymofo in maintenance mode, but i just thought that since the functionality of getting the default values, making a new record and run the corresponding function on insert is already there, it would be easy for you to include it as standard functionality.

Anyway, since it can be done with js i will also give it a try myself.

I am not so creative or proficient in js but maybe i can pull it of.

I will keep you posted.

Best Regards

**Comment by lazymofo** [comment]
It appears you can add/overide defaults like this:

$lm->form_default_value['contact_email'] = 'this is the new default on add
form;
