### ISSUE TITLE
Edits not committed

### ISSUE THREAD

**Issue by kpsgis** [lazymofo/datagrid#9]
I'm getting no errors, and it acts like it's updating, but the changes are not saving. Want to change the Y to a N (the the data isn't used in reports). Other tables are acting correctly for edits, but this one has a custom add page, didn't know if that is related to this annomally.  Since there are differences, I made the 
change:
    `public $grid_add_link    = "<a href='addticket1.php' class='lm_grid_add_link'>Add a Record</a>";`
and saved as lazy_mofo26_tkt.php and all other pages use the unchanged lazy_mofo.php

`<?php

require('dist/lazy_mofo26_tkt.php');
// create LM object, pass in PDO connection
$lm = new lazy_mofo($elcon); 

// table name for updates, inserts and deletes
$lm->table = 'tbltkts';

// identity / primary key for table
$lm->identity_name = 'tktid';

// optional, make friendly names for fields
$lm->rename['linkid'] = 'Shipper';
$lm->rename['itemnumb'] = 'Item';
$lm->rename['ticknumb'] = 'TKT #';
$lm->rename['tickdate'] = 'TKT Date';
$lm->rename['grosswt'] = 'Gross WT';
$lm->rename['tarewt'] = 'Tare WT';
$lm->rename['netwt'] = 'Net WT';
$lm->rename['persmoist'] = '% Moisture';
$lm->rename['lname'] = 'Business/Last Name';
$lm->rename['fname'] = 'First Name';

//addtional html inside form after form buttons
//$form_additional_html = 'test';

// optional, define input controls on the form
$lm->form_input_control['entby'] = '--whoent';

function whoent($column_name, $value, $command, $called_from){
    // $column_name: field name
    // $value: field value  
    // $command: full command as defined in the arrays: form_input_control, grid_input_control, or grid_output_control
    // $called_from: which function called this user function; form, or grid
    global $lm;
    $val = $lm->clean_out($_SESSION['user']['username']);
    return "<input type='text' name='$column_name' value='$val' size='30'>";
}
//$lm->form_input_control['inuse'] = "select Y, 'Yes' union select N, 'No' union select H, 'Maybe'; --radio";
$lm->form_input_control['invID'] = 'select itemnumb, itemdesc, stdUnit from tblinventory order by itemdesc asc; --select';
$lm->form_input_control['tktid'] = 'select tktid, lname, fname from tblacts; --select';
$lm->form_input_control['inUse'] ='Y';

// change back button to read "Cancel"
$lm->form_back_button = "<input type='button' value='Cancel' class='lm_button dull' onclick='_back();'>";
$lm->form_delete_button = "";

// alter link text
$lm->grid_add_link = str_replace('Add a Record', 'Add New', $lm->grid_add_link);
$lm->grid_edit_link = str_replace('[edit]', 'Edit', $lm->grid_edit_link);

// hide delete and export links
$lm->grid_delete_link = "";
$lm->grid_export_link = "";

// change success message
$lm->form_text_record_added = "New Record Added";
$lm->grid_text_record_added = "New Record Added";

// optional, define editable input controls on the grid
//$lm->grid_input_control['inUse'] = '--checkbox';

// optional, define output control on the grid 
/*$lm->grid_output_control['contact_email'] = '--email'; // make email clickable
$lm->grid_output_control['photo'] = '--image'; // image clickable  */

// new in version >= 2015-02-27 all searches have to be done manually
$lm->grid_show_search_box = true;

// optional, query for grid(). LAST COLUMN MUST BE THE IDENTITY for [edit] and [delete] links to appear
$lm->grid_sql = "
select 
  t.tktid
, t.ticknumb
, t.tickdate
, a.lname
, a.fname
, i.itemDesc
, t.grosswt
, t.tarewt
, t.netwt
, t.percmoist
, t.inUse
, t.tktid
from  tbltkts t 
left  
join  tblacts a 
on    t.linkid = a.autoid 
join  tblinventory i 
on    t.invID = i.itemnumb 
where t.inUse ='Y'
and (coalesce(a.lname, '') like :_search 
or    coalesce(i.itemDesc, '') like :_search 
or    coalesce(t.ticknumb, '') like :_search )
order by t.tickdate desc
";
$lm->grid_sql_param[':_search'] = '%' . trim(@$_REQUEST['_search']) . '%';

// optional, define what is displayed on edit form. identity id must be passed in also.  
$lm->form_sql = "
select 
  tktid
, ticknumb
, tickdate
, invID
, linkid
, grosswt
, tarewt
, netwt
, percmoist
, entered
, entby
, inUse
from  tbltkts 
where tktid = :tktid
";
$lm->form_sql_param[":$lm->identity_name"] = @$_REQUEST[$lm->identity_name]; 

// optional, validation. input:  regular expression (with slashes), error message, tip/placeholder
// first element can also be a user function or 'email'
$lm->on_insert_validate['ticknumb'] = array('/.+/', 'Missing Ticket Number', ' Required'); 
$lm->on_insert_validate['tickdate'] = array('/^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/', 'Invalid date', 'Required', true); 
$lm->on_insert_validate['grosswt'] = array('/[0-9]/', 'Missing weight', 'Required', true); 
$lm->on_insert_validate['invID'] = array('/[0-9]/', 'Missing Item', 'Required', true); 
$lm->on_insert_validate['linkid'] = array('/[0-9]/', 'Missing shipper', 'Required', true); 
$lm->on_insert_validate['tarewt'] = array('/[0-9]/', 'Missing weight', 'Required', true);
$lm->on_insert_validate['percmoist'] = array('/[0-9]/', 'Missing moisture percent', 'Required', true);  
$lm->on_insert_validate['inUse'] = array('/[YN]/', 'Required', true); 

// copy validation rules to update - same rules
$lm->on_update_validate = $lm->on_insert_validate;  

$lm->return_to_edit_after_insert = false;
$lm->return_to_edit_after_update = false;

// use the lm controller
$lm->run();
?>`

What should I check first? Thanks.

**Comment by lazymofo** [comment]
I think this is the form input control you're looking for:

$lm->form_input_control['inuse'] = "select 'Y', 'Yes' union select 'N',
'No'; --radio";

You were missing quotes around the Y and N.

The commands to populate the input controls are just SQL statements, so you
can test them in MySQL to make sure they work before using them.

**Comment by kpsgis** [comment]
Thanks, I like the looks of the radio button on the inUse field. That works. It still doesn't save the edits. I'm thinking it's because the data type is varchar 1 and in another area can be archived/marked historic so they are no longer used in the reports. So I made your form_input_control code to read:
`$lm->form_input_control['inUse'] = "select 'Y', 'Yes' union select 'N',
'No' union select 'H', 'Historic'; --radio";`
but no matter which radio I choose, the value remains Y in the database. Is it expecting Boolean data type because it's Y and N? Or because I have default value set in mysql? (just checked that theory removing the default in phpMyAdmin, but it did not save the change from Y to N or to H.)

**Comment by lazymofo** [comment]
Check your table to make sure inUse is char or varchar. Maybe inUse is an
int.

If that does not work maybe you can print the update query before it runs
to see if anything looks strange; you'd have to add a var_dump and die into
sql_update() before it calls query().

**Comment by kpsgis** [comment]
Thanks, I tried that and never found the right place, or at least I never saw the results of var_dump. I discovered that the code had 'inUse' and the table was 'inuse', then I also found this line - getting the case the same and removing $lm->form_input_control['inUse'] ='Y'; and it works like a charm.

Thanks again.
