### ISSUE TITLE
Ajax search

### ISSUE THREAD

**Issue by erikssonpontus** [lazymofo/datagrid#90]
Is it possible to add Ajax-search?

**Comment by lazymofo** [comment]
[There are no built in features, but you could disable pagination and add javascript to hide and show rows according to the search. Here's a demo attached.
[js_search.txt](https://github.com/lazymofo/datagrid/files/10311261/js_search.txt)

**Comment by erikssonpontus** [comment]
This is awesome!

When I apply your code then "Save changes" and "Update" stop working.
Any solution for this?

**Comment by lazymofo** [comment]
here are some tweaks that should fix things
[js_search.txt](https://github.com/lazymofo/datagrid/files/10329891/js_search.txt)
