### ISSUE TITLE
Question about decimal point

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#91]
Hello Ian,

I hope the best for you and Happy new Year !

I wanted to ask you about the decimal point.

I cannot find a setting for the decimal point, similar to what you have for the date locale.

As a result the lazymofo accepts only the point (.) as a decimal separator as it is used in the en-us locale. (i think ?)

Is there a way to override this and be able to use the comma (,) as a decimal separator as we do in e.g Greece ?

Best Regards

**Comment by lazymofo** [comment]
Theophilos,

I'll look into this soon. I'd think if the server locale was set to Greece,
then it would automatically use "," for decimals, I assume you tried this
already. The library may need a fix. I'll let you know what I find.

Thanks,
Ian

**Comment by tplevrak** [comment]
Thank you a lot Ian.

As you said i have tried this to PCs which are set to Greek Locale but it still needs the point(.) as a decimal separator.

But regardless of that, a way to explicitly declare something like that is useful.

In the case of the date, i have been able to create a per user setting of the date locale regardless of the pc settings, and that is helping my application to remain consistent.

It would be really nice to have this with the decimal separator.

Best Regards

**Comment by lazymofo** [comment]
The decimal separator fix is almost ready. It should be rolled out tonight.

**Comment by lazymofo** [comment]
I think this fix/feature is completed. Hopefully it works as needed for you.
Details:
https://rawgit.com/lazymofo/datagrid/master/index.html#decimal_separator

**Comment by tplevrak** [comment]
Good morning Ian,

And thank you once again for the best data grid for php and for your prompt response and addition of the feature.

I am going to install it next week and make good use of it.

Best Regards !!!

**Comment by lazymofo** [comment]
No problem. Thanks for submitting that issue!

I thought localization setting would automatically take care of this kind
of issue. I was surprised to find out SQL only wants to use a period for
decimal separator; probably since commas are a delimiter in SQL.
