### ISSUE TITLE
multiselect search box values won't carry around in the URL

### ISSUE THREAD

**Issue by sarangtc** [lazymofo/datagrid#92]
Hi,

using the `$lm->grid_search_box` variable, I added some custom search inputs to a page, all inputs work fine, except multiselect ones. The parameter is not carried forward in next page, showall etc. URLs even though the parameter is set in the `$lm->query_string_list` variable

**Comment by sarangtc** [comment]
This can be handled by modifying the get_qs function by adding the following 5 lines:
```
function get_qs($query_string_list = '_order_by,_desc,_offset,_search,_pagination_off')
    {

        // purpose: render querysting. user selections for order, search, and page are carry from page to page. 
        // this maintains search state while paging, updating, etc...

        // append users additions
        if (mb_strlen($this->query_string_list) > 0)
            $query_string_list .= ',' . $this->query_string_list;

        $get = '';
        $arr = explode(',', trim($query_string_list, ','));
        foreach ($arr as $var){
+		$val = @$_REQUEST[$var] ?? '';
+			if ( !is_array($val) && mb_strlen($val) > 0 ){
				$get .= "&$var=" . urlencode($val);
+			} elseif( is_array($val) ) {
+				foreach( $val as $myval ){
+					$get .= "&$var".urlencode("[]")."=" . urlencode($myval);
+				}
			}
		}

        return ltrim($get, '&');
    }
```

If the existing mb_strlen returns false, this then checks if the parameter is an array (which would have been obtained by adding "[]" to the parameter input name). and adds each value to the query string with the additional urlencoded "[]" on the parameter name.

Note: I have also defined a `$val` variable to make it simpler to follow

**Comment by sarangtc** [comment]
So I suggest the `get_qs` function be modified as suggested above so that it does not break in such cases

**Comment by lazymofo** [comment]
I'll take a look at this in a couple weeks. Sorry for the delay, summer
vacation.
Thanks for submitting this bug and fix!

**Comment by sarangtc** [comment]
I have updated the function slightly to make it php8 compatible, as in php8 mb_strlen on array throws an error, so I have added a check for that

**Comment by lazymofo** [comment]
Thanks for your help! I've implemented a fix based on your code. 
I didn't want to use the null coalesce operator since this project still says it supports php 5.
