### ISSUE TITLE
Query re: adding mysql function on after insert / update

### ISSUE THREAD

**Issue by DEHWall** [lazymofo/datagrid#93]
Excellent utility for database editing!

Not an issue - just need some help with the following:

I need the ability to change the password field which is encrypted with AES_ENCRYPT()
e.g.
select Userid, Name, AES_DECRYPT(password,'key value') password.... from users (etc.)

After an update to the 'password' field - how would I invoke AES_ENCRYPT('new password value', 'key value') in the MySQL update?

Hope you can help
Many thanks

**Comment by lazymofo** [comment]
Here's a couple ideas, it's untested code.
I should add more demo examples to the project.

FYI, you're not supposed to encrypt passwords, you should hash them
instead.
I'd recommend php's password_hash().


// option 1 - alter info before it's added to the database
$lm->on_insert_user_function = 'on_insert';
$lm->on_update_user_function = 'on_update';


function on_insert(){

    $_POST['password'] = password_hash($_POST['password'],
PASSWORD_DEFAULT);

}


function on_update(){

    $password = $_POST['password'] ?? '';

    // no password then remove the key from the post so we don't blank out
the existing entry
    if(strlen($password) == 0){
        unset($_POST['password']);
        return;
    }

    // validate
    if(strlen($password) < 2)
        return 'Password too short';

    // alter the global $_POST array
    $_POST['password'] = password_hash($_POST['password'],
PASSWORD_DEFAULT);

}





// option 2 - alter data AFTER it's been added to the database
$lm->after_insert_user_function = 'after_insert';
$lm->after_update_user_function = 'after_update';

function after_insert($id){

    global $lm;
    $sql = "update table set password = my_hash(:password) where id = :id";
    $lm->query($sql, array(':password' => $password, ':id' => $id));

}

function after_update(){

    global $lm;
    $id = $_POST['id'];
    $password = $_POST['password'] ?? '';

    // quit if there was no password posted, btw, we can't return
validation errors in after_ hooks, the data has already been saved into the
database
    if(strlen($password) <= 0)
        return;

    $sql = "update table set password = my_hash(:password) where id = :id";
    $lm->query($sql, array(':password' => $password, ':id' => $id));

}

**Comment by DEHWall** [comment]
Hi Ian,

 

Many thanks for the prompt reply.

 

I have taken your advice on using password_hash / password_verify – using option 1 and modifying my login script and it worked perfectly.

 

Many thanks again.

 

Ps – is there anyway that I can make use of the text-transform on input text fields?

text-transform: uppercase;

text-transform: lowercase;

text-transform: capitalize;

 

Best Regards

Dave

**Comment by lazymofo** [comment]
>>Ps – is there anyway that I can make use of the text-transform on input
text fields?

Yes, you can apply any css you would like.

Example: #lm input[type=text] { text-transform: uppercase; }

**Comment by DEHWall** [comment]
Thanks Ian

Will give that a go

Regards
Dave

Regards
David
________________________________

**Comment by DEHWall** [comment]
Hi Ian,

 

I needed it for specific fields, so the following worked:

 

Set up new input control  –upper

 

$lm->form_input_control[‘fieldname’] = '--upper';

 

And added to lazy_mofo.php line 1625:

        elseif ($cmd == 'upper')

            return "<input style='text-transform:uppercase;' type='text' name='$column_name' class='$class' value='" . $this->clean_out($value) . "' size='$size' $max_length placeholder='$validate_placeholder'>$validate_error $validate_placeholder_alternative";

 

Many thanks

 

Dave
