### ISSUE TITLE
Difference between Grid and CSV Export outputs.

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#96]
Dear Ian, i hope that you are well.

I wanted to ask a question about something that happened to a lm grid that i have setup.

In an lm grid that i have setup, i have included two columns that for each of them i have a custom function to change the output in the grid., and i have renamed them to give them a friendly name.

When the grid is viewed onscreen everything shows ok, both column content and header.

But when i export the grid in csv format, these two column show up as they originally are, without the extra formatting i have in the custom function and also their title is not renamed as it is declared in the grid php file.

Do i miss something about export ?

Best Regards

**Comment by lazymofo** [comment]
You're right, there's a shortcoming there. The grid passes the query result
to the export method; the grid output controls are NOT rendered.

Maybe this will help, you could add a query that's specific to exporting:

if(($_GET['_export'] ?? 0) == 1){
   // query specific to desired export style
}
else {
   // default existing query
}

**Comment by tplevrak** [comment]
Dear Ian,
Thank you again for your response and advice.

Unfortunately in this case i am not using the format function for formatting but rather for changing the output value with if/then statements so i have to have the formatted output in both the grid and the .csv.

Of course it is good for me to know that formatting functions do not export to csv for future use.
(Or else i always doubt myself if i am doing it correctly).

So now instead of the formatting functions i changed my grid sql to include the if/then statements to get the wanted values to appear in both the grid and .csv

Thank you again and Best Regards !!!
