### ISSUE TITLE
Weird Bug that i cannot figure out

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#97]
Dear Ian,

 I hope that you are well.

I wanted to ask you something that is very weird, at least to me.

I am developing a small application and i have the lazymofo included in the webpage.
(actually it is the first time i am using lazymofo directly, up until now i only used iframes.)

I have a page with a lazymofo that works well and loads a s expected.

But when i try to save the changes, the changes are saved but the page loads up to a certain point only, and i get a warning from the apache about headers already sent.

 _PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/microapp.mobiak.com/tf_mbk_ma/tf_html/tf_main_user_page/tf_projects_view.php:55)_

Now, there is nothing wrong or special in the line suggested.
(as you can see in the file i attached).

Plus it only has a problem loading when saving. By reloading the same url it works as expected.

I have uploaded the code of the page in a txt file.

Can you tell me if it is a lazymofo issue, and if yes, how to work it out ?

Best Regards

[teo.txt](https://github.com/lazymofo/datagrid/files/14482925/teo.txt)

**Comment by lazymofo** [comment]
I think I'd have to have all the code to find the root of this issue.

Typically this is caused by html or whitespace output before a header()
call; header is often used for redirects.
Try an ob_start() call at the top of the script.

https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

**Comment by tplevrak** [comment]
Dear Ian,

Thank you very much for your response.

Your advice of using ob_start() at the start of the script, worked.

I am not sure what is outputted before the header but whatever it is, it is now resolved.

Thank you very much once again for your advice and your awesome work !

Best Regards
